New version, including bumped imap version. Note that the --with-apxs{2} options are now mandatory, since otherwise php won't build the DSO's.
git-svn-id: svn+ssh://tchan@foo-projects.org/var/svn/lunar/moonbase/trunk@4357 fe636330-a7f5-0310-8408-fdd8893149bb

diff --git a/compilers/php/CONFIGURE b/compilers/php/CONFIGURE
--- a/compilers/php/CONFIGURE
+++ b/compilers/php/CONFIGURE
@@ -1,10 +1,14 @@
-if  !  grep  -q  CONFIGURED  $MODULE_CONFIG;  then
 
-  if    module_installed  apache  ||
-        module_installed  apache-mod_ssl
-  then 
-    OPTS="$OPTS --with-apxs=/usr/sbin/apxs"
-  fi
+# The following ALWAYS needs to be set, so we put it outside of the CONFIGURED
+# statement, otherwise php fails to install against apache2 on the first
+# update. -- 20031105 - sofar
+if module_installed apache || module_installed apache-mod_ssl ; then 
+  OPTS="$OPTS --with-apxs=/usr/sbin/apxs"
+elif module_installed apache2 ; then
+  OPTS="$OPTS --with-apxs2=/usr/sbin/apxs"
+fi
+
+if  !  grep  -q  CONFIGURED  $MODULE_CONFIG;  then
 
   if  query  "Install ftp support?" y;  then
     OPTS="$OPTS --enable-ftp"
