Exchanging the tar checking for a far superiour one
git-svn-id: svn+ssh://tchan@foo-projects.org/var/svn/lunar/moonbase/trunk@10260 fe636330-a7f5-0310-8408-fdd8893149bb

diff --git a/kernel/linux-2.4-agr/PRE_BUILD b/kernel/linux-2.4-agr/PRE_BUILD
--- a/kernel/linux-2.4-agr/PRE_BUILD
+++ b/kernel/linux-2.4-agr/PRE_BUILD
@@ -16,11 +16,13 @@ rm -f /usr/src/linux
 ln -s $SOURCE_DIRECTORY /usr/src/linux
 cd $SOURCE_DIRECTORY
 
-# Yes, this is a workaround. Blame tar.
-if [ "$(installed_version tar)" == "1.15.1" ]; then
-  tar jxf $SOURCE_CACHE/$SOURCE --no-same-owner --no-same-permissions --strip-components=1
+# Check wether we're running an up-to-date tar
+if [ `lvu installed tar | cut -d. -f2` -ge 15 ]; then
+  tar xf $SOURCE_CACHE/$SOURCE --no-same-owner \
+  --no-same-permissions --strip-components=1
 else
-  tar jxf $SOURCE_CACHE/$SOURCE --no-same-owner --no-same-permissions --strip-path=1
+  echo "${PROBLEM_COLOR}Error:${DEFAULT_COLOR} Please update your tar module"
+  exit 1
 fi
 
 if [ -f $CONFIG_CACHE/.config ]; then
diff --git a/kernel/linux-2.6/PRE_BUILD b/kernel/linux-2.6/PRE_BUILD
--- a/kernel/linux-2.6/PRE_BUILD
+++ b/kernel/linux-2.6/PRE_BUILD
@@ -16,7 +16,14 @@ rm -f /usr/src/linux
 ln -s $SOURCE_DIRECTORY /usr/src/linux
 cd $SOURCE_DIRECTORY
 
-tar xf $SOURCE_CACHE/$SOURCE --no-same-owner --no-same-permissions --strip-components=1
+# Check wether we're running an up-to-date tar
+if [ `lvu installed tar | cut -d. -f2` -ge 15 ]; then
+  tar xf $SOURCE_CACHE/$SOURCE --no-same-owner \
+  --no-same-permissions --strip-components=1
+else
+  echo "${PROBLEM_COLOR}Error:${DEFAULT_COLOR} Please update your tar module"
+  exit 1
+fi
 
 if  [ -f $CONFIG_CACHE/.config.2.6.stable ]; then
     cp $CONFIG_CACHE/.config.2.6.stable $BUILD_DIRECTORY/linux/.config;
