ffmpeg: version bumped to 2.8.

diff --git a/virtual/VirtualBox/VirtualBox b/virtual/VirtualBox/VirtualBox
--- a/virtual/VirtualBox/VirtualBox
+++ b/virtual/VirtualBox/VirtualBox
@@ -16,8 +16,8 @@ PATH="/usr/bin:/bin:/usr/sbin:/sbin"
 CONFIG="/etc/vbox/vbox.cfg"
 
 if [ ! -r "$CONFIG" ]; then
-    echo "Could not find VirtualBox installation. Please reinstall."
-    exit 1
+  echo "Could not find VirtualBox installation. Please reinstall."
+  exit 1
 fi
 
 . "$CONFIG"
@@ -26,9 +26,9 @@ fi
 #       because the user might not want to run a VM but only change VM params!
 
 if [ "$1" = "shutdown" ]; then
-    SHUTDOWN="true"
+  SHUTDOWN="true"
 elif ! lsmod|grep -q vboxdrv; then
-    cat << EOF
+  cat << EOF
 WARNING: The vboxdrv kernel module is not loaded. Either there is no module
          available for the current kernel (`uname -r`) or it failed to
          load. Please recompile the kernel module and install it by
@@ -38,36 +38,36 @@ WARNING: The vboxdrv kernel module is not loaded. Either there is no module
          You will not be able to start VMs until this problem is fixed.
 EOF
 elif [ ! -c /dev/vboxdrv ]; then
-    cat << EOF
+  cat << EOF
 WARNING: The character device /dev/vboxdrv does not exist. Try
 
            sudo /etc/init.d/virtualbox restart
 
          and if that is not successful, try to re-install the package.
 
-	 You will not be able to start VMs until this problem is fixed.
+         You will not be able to start VMs until this problem is fixed.
 EOF
 elif [ ! -w /dev/vboxdrv ]; then
-    if [ "`id | grep vboxusers`" = "" ]; then
-        cat << EOF
+  if [ "`id | grep vboxusers`" = "" ]; then
+    cat << EOF
 WARNING: You are not a member of the "vboxusers" group.  Please add yourself
          to this group before starting VirtualBox.
 
-	 You will not be able to start VMs until this problem is fixed.
+         You will not be able to start VMs until this problem is fixed.
 EOF
-    else
-        cat << EOF
+  else
+    cat << EOF
 WARNING: /dev/vboxdrv not writable for some reason. If you recently added the
          current user to the vboxusers group then you have to logout and
-	 re-login to take the change effect.
+         re-login to take the change effect.
 
-	 You will not be able to start VMs until this problem is fixed.
+         You will not be able to start VMs until this problem is fixed.
 EOF
-    fi
+  fi
 fi
 
 if [ -f /etc/vbox/module_not_compiled ]; then
-    cat << EOF
+  cat << EOF
 WARNING: The compilation of the vboxdrv.ko kernel module failed during the
          installation for some reason. Starting a VM will not be possible.
          Please consult the User Manual for build instructions.
@@ -78,21 +78,21 @@ export LD_LIBRARY_PATH="$INSTALL_DIR/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
 
 SERVER_PID=`ps -U \`whoami\` | grep VBoxSVC | awk '{ print $1 }'`
 if [ -z "$SERVER_PID" ]; then
-    # Server not running yet/anymore, cleanup socket path.
-    # See IPC_GetDefaultSocketPath()!
-    if [ -n "$LOGNAME" ]; then
-        rm -rf /tmp/.vbox-$LOGNAME-ipc > /dev/null 2>&1
-    else
-        rm -rf /tmp/.vbox-$USER-ipc > /dev/null 2>&1
-    fi
+  # Server not running yet/anymore, cleanup socket path.
+  # See IPC_GetDefaultSocketPath()!
+  if [ -n "$LOGNAME" ]; then
+    rm -rf /tmp/.vbox-$LOGNAME-ipc > /dev/null 2>&1
+  else
+    rm -rf /tmp/.vbox-$USER-ipc > /dev/null 2>&1
+  fi
 fi
 
 if [ "$SHUTDOWN" = "true" ]; then
-    if [ -n "$SERVER_PID" ]; then
-        kill -TERM $SERVER_PID
-        sleep 2
-    fi
-    exit 0
+  if [ -n "$SERVER_PID" ]; then
+    kill -TERM $SERVER_PID
+    sleep 2
+  fi
+  exit 0
 fi
 
 chgrp vboxusers /dev/vboxdrv
