Should fix the problems... cause: new pidfile code of sendmail, yeck!
git-svn-id: svn+ssh://tchan@foo-projects.org/var/svn/lunar/moonbase/trunk@3731 fe636330-a7f5-0310-8408-fdd8893149bb

diff --git a/mail/sendmail/init.d/sendmail b/mail/sendmail/init.d/sendmail
--- a/mail/sendmail/init.d/sendmail
+++ b/mail/sendmail/init.d/sendmail
@@ -17,8 +17,49 @@ reload () {
 }
 
 start () {
-	newaliases
-	default_start
+	if [ -f /etc/mail/aliases ] ; then
+	  newaliases
+	fi
+	if [ -f /etc/mail/virtusers ] ; then
+	  makemap hash /etc/mail/virtusers.db < /etc/mail/virtusers
+	fi
+	if [ -f /etc/mail/genericstable ] ; then
+	  makemap hash /etc/mail/genericstable.db < /etc/mail/genericstable
+	fi
+	if [ -f /etc/mail/access ] ; then
+	  makemap hash /etc/mail/access.db < /etc/mail/access
+	fi
+	echo -n "Starting sendmail: "
+	if [ -f $PIDFILE ] ; then
+	  echo -e "$PIDFILE exists!$RESULT_FAIL"
+	  exit 1
+	fi
+	if $(/bin/pgrep -P 1 sendmail &> /dev/null) ; then 
+	  echo -e "Already running$RESULT_FAIL"
+	  exit 1
+	fi
+	/usr/sbin/sendmail $ARGS &&
+	  echo -e $RESULT_OK ||
+	  echo -e $RESULT_FAIL
+}
+
+stop () {
+	echo -n "Stopping sendmail: "
+	if [ -f $PIDFILE ] ; then
+	  PID=$(head -1 $PIDFILE)
+	  if [ -d /proc/$PID ] ; then
+	    if kill -TERM $PID ; then
+	      rm $PIDFILE
+	      echo -e $RESULT_OK
+	    else
+	      echo -e "kill failed$RESULT_FAIL"
+	    fi
+	  else
+	    echo -e "can't find PID$RESULT_FAIL"
+	  fi
+	else
+	  echo -e "can't find PID$RESULT_FAIL"
+	fi
 }
 
 . /lib/lsb/init-functions
